### ISSUE TITLE
tap and hold issue

### ISSUE THREAD

**Issue by baietoo** [PixelsCommander/PrayerWheel#5]
Hi, coming here from devtalks.
im on samsung s10e on chrome and this happens:
* tap and hold and the word 'may' comes up as a sugestion by google
   * the wheel cannot be spun anymore unless you refresh the page
![WIN_20200610_16_06_23_Pro](https://user-images.githubusercontent.com/22468549/84271201-7eaae700-ab34-11ea-9923-26469448a76b.jpg)

have a good one!

**Comment by PixelsCommander** [comment]
Hey, sorry it took so long. Just made a fix
